import globals from "globals";
//import js from "@eslint/js";
import react from "eslint-plugin-react";
import jest from "eslint-plugin-jest";
import typescript from "typescript-eslint";

const k_commonRules = {
  eslint: {
    // - see: https://eslint.org/docs/latest/rules/
    // Possible logic errors:
    "array-callback-return": "error",
    "constructor-super": "error",
    "no-this-before-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-promise-executor-return": "error",
    "no-await-in-loop": "warn",
    "no-class-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-constructor-return": "error",
    "no-control-regex": "warn",
    "no-debugger": "error",
    //"no-dupe-args": "error", // handled by TypeScript compiler
    //"no-dupe-class-members": "error", // handled by TypeScript compiler
    //"no-dupe-keys": "error", // handled by TypeScript compiler
    "no-dupe-else-if": "error",
    "no-duplicate-case": "error",
    "no-fallthrough": [
      "error",
      {
        allowEmptyCase: true,
        commentPattern: "^fallthrough$",
        reportUnusedFallthroughComment: true,
      },
    ],
    "no-duplicate-imports": "warn",
    "no-invalid-regexp": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "warn",
    "no-useless-backreference": "error",
    "no-misleading-character-class": "error",
    "no-regex-spaces": "warn",
    "no-useless-escape": "error",
    "no-ex-assign": "error",
    "no-unsafe-finally": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-new-native-nonconstructor": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "warn",
    "no-template-curly-in-string": "error",
    "no-unassigned-vars": "error",
    "no-undef": "error",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "error",
    "no-unreachable-loop": "error",
    "no-unreachable": "warn",
    "no-unused-private-class-members": "warn",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "require-atomic-updates": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    // Suggestions:
    "no-case-declarations": "error",
    "no-delete-var": "error",
    "no-empty": "error",
    "no-empty-static-block": "error",
    eqeqeq: ["error", "smart"],
    "no-extra-boolean-cast": "warn",
    "no-redeclare": "error",
    "no-global-assign": "error",
    "no-shadow-restricted-names": "error",
    "no-implicit-coercion": "warn",
    "no-nonoctal-decimal-escape": "error",
    "no-useless-catch": "error",
    "no-unused-labels": "error",
    "no-with": "error",
    "require-yield": "warn",
    // TODO: review rest of available 'Suggestions' rules
  },
  typescript: {
    // Some ESLint core rules with the same name are turned off because "you
    //  must disable the base rule as it can report incorrect errors."
    // - see: https://typescript-eslint.io/rules/
    // - see: https://typescript-eslint.io/users/configs/#recommended-configurations
    // Strict:
    "@typescript-eslint/no-confusing-void-expression": "warn",
    "@typescript-eslint/no-invalid-void-type": "error",
    "@typescript-eslint/no-meaningless-void-operator": "error",
    "@typescript-eslint/no-deprecated": "warn",
    "@typescript-eslint/no-dynamic-delete": "warn",
    "@typescript-eslint/no-misused-spread": "error",
    "@typescript-eslint/no-mixed-enums": "warn",
    "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
    "@typescript-eslint/no-non-null-assertion": "warn",
    "@typescript-eslint/no-unnecessary-condition": "warn",
    "@typescript-eslint/no-unnecessary-template-expression": "warn",
    "@typescript-eslint/no-unnecessary-type-conversion": "error",
    "@typescript-eslint/no-unnecessary-type-parameters": "warn",
    "no-useless-constructor": "off",
    "@typescript-eslint/no-useless-constructor": "error",
    "@typescript-eslint/prefer-literal-enum-member": "warn",
    "@typescript-eslint/prefer-reduce-type-parameter": "error",
    "@typescript-eslint/prefer-return-this-type": "error",
    "@typescript-eslint/related-getter-setter-pairs": "warn",
    "@typescript-eslint/return-await": "error",
    "@typescript-eslint/unified-signatures": "warn",
    "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
    // Recommended:
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/ban-ts-comment": "error",
    "no-array-constructor": "off",
    "@typescript-eslint/no-array-constructor": "error",
    "@typescript-eslint/no-array-delete": "error",
    "@typescript-eslint/no-base-to-string": "error",
    "@typescript-eslint/no-duplicate-enum-values": "error",
    "@typescript-eslint/no-duplicate-type-constituents": "error",
    "@typescript-eslint/no-redundant-type-constituents": "error",
    "@typescript-eslint/no-empty-object-type": "error",
    "@typescript-eslint/no-explicit-any": "warn",
    "@typescript-eslint/no-extra-non-null-assertion": "warn",
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/no-for-in-array": "error",
    "@typescript-eslint/no-implied-eval": "error",
    "@typescript-eslint/no-misused-new": "error",
    "@typescript-eslint/no-misused-promises": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-this-alias": "warn",
    "@typescript-eslint/no-unnecessary-type-assertion": "error",
    "@typescript-eslint/no-unnecessary-type-constraint": "error",
    "@typescript-eslint/no-unsafe-argument": "error",
    "@typescript-eslint/no-unsafe-assignment": "error",
    "@typescript-eslint/no-unsafe-call": "error",
    "@typescript-eslint/no-unsafe-declaration-merging": "error",
    "@typescript-eslint/no-unsafe-enum-comparison": "error",
    "@typescript-eslint/no-unsafe-function-type": "error",
    "@typescript-eslint/no-unsafe-member-access": "error",
    "@typescript-eslint/no-unsafe-return": "error",
    "@typescript-eslint/no-unsafe-unary-minus": "error",
    "no-unused-expressions": "off",
    "@typescript-eslint/no-unused-expressions": "warn",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "@typescript-eslint/no-wrapper-object-types": "error",
    "@typescript-eslint/only-throw-error": "error",
    "@typescript-eslint/prefer-as-const": "error",
    "@typescript-eslint/prefer-namespace-keyword": "warn",
    "@typescript-eslint/prefer-promise-reject-errors": "warn",
    "require-await": "off",
    "@typescript-eslint/require-await": "error",
    "@typescript-eslint/restrict-plus-operands": "error",
    "@typescript-eslint/restrict-template-expressions": "warn",
    "@typescript-eslint/triple-slash-reference": "warn",
    "@typescript-eslint/unbound-method": ["warn", { ignoreStatic: true }],
    // Our rules:
    "@typescript-eslint/switch-exhaustiveness-check": "error",
    "@typescript-eslint/adjacent-overload-signatures": "warn",
    "@typescript-eslint/array-type": "warn",
    "@typescript-eslint/class-literal-property-style": ["error", "getters"],
    "class-methods-use-this": "off",
    "@typescript-eslint/class-methods-use-this": "off",
    "@typescript-eslint/consistent-generic-constructors": [
      "warn",
      "constructor",
    ],
    "@typescript-eslint/consistent-indexed-object-style": ["warn", "record"],
    "@typescript-eslint/consistent-type-assertions": [
      "warn",
      { assertionStyle: "as" },
    ],
    "@typescript-eslint/consistent-type-definitions": ["warn", "interface"],
    "@typescript-eslint/consistent-type-exports": "warn",
    "@typescript-eslint/consistent-type-imports": [
      "warn",
      { prefer: "type-imports" },
    ],
    "@typescript-eslint/no-import-type-side-effects": "error",
    "dot-notation": "off",
    "@typescript-eslint/dot-notation": [
      "warn",
      { allowIndexSignaturePropertyAccess: true },
    ],
    "@typescript-eslint/explicit-member-accessibility": [
      "error",
      { accessibility: "no-public" },
    ],
    "@typescript-eslint/explicit-module-boundary-types": "warn",
    "init-declarations": "off",
    "@typescript-eslint/init-declarations": ["error", "always"],
    "@typescript-eslint/method-signature-style": ["error", "property"],
    "@typescript-eslint/naming-convention": [
      "warn",
      {
        selector: "variable",
        modifiers: ["global", "const"],
        types: ["array", "boolean", "number", "string"],
        prefix: ["k_"],
        format: ["camelCase"],
      },
      {
        selector: ["enum", "interface", "class", "typeParameter", "typeAlias"],
        format: ["PascalCase"],
      },
      {
        selector: ["enumMember"],
        format: ["camelCase"],
      },
      {
        selector: ["typeProperty"],
        modifiers: ["abstract"],
        leadingUnderscore: "allow",
        format: ["camelCase", "PascalCase"],
      },
      {
        selector: [
          "classProperty",
          "classicAccessor",
          "classMethod",
          "objectLiteralMethod",
        ],
        leadingUnderscore: "allow",
        format: ["camelCase"],
      },
      //{
      //  selector: "objectLiteralProperty",
      //  leadingUnderscore: "allow",
      //  format: null,
      //  custom: {
      //    match: true,
      //    regex: "^[a-z]([_-]?[A-Za-z])*$"
      //  }
      //},
      {
        selector: ["function", "import"],
        leadingUnderscore: "allow",
        format: ["camelCase", "PascalCase"],
      },
      {
        selector: ["variable", "parameter"],
        filter: {
          match: false,
          regex: "^k_",
        },
        leadingUnderscore: "allow",
        format: ["camelCase", "PascalCase"],
      },
    ],
    "@typescript-eslint/no-confusing-non-null-assertion": "error",
    "no-loop-func": "off",
    "@typescript-eslint/no-loop-func": "error",
    "no-magic-numbers": "off",
    "@typescript-eslint/no-magic-numbers": "off",
    //"@typescript-eslint/no-magic-numbers": [
    //  "warn",
    //  {
    //    enforceConst: true,
    //    ignoreArrayIndexes: true,
    //    ignoreDefaultValues: true,
    //    ignoreEnums: true,
    //    ignoreNumericLiteralTypes: true,
    //    ignoreReadonlyClassProperties: true,
    //    ignoreTypeIndexes: true,
    //    detectObjects: false,
    //    ignoreClassFieldInitialValues: false,
    //  },
    //],
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": [
      "warn",
      {
        //builtinGlobals: true,
        hoist: "all",
      },
    ],
    "@typescript-eslint/no-unnecessary-parameter-property-assignment": "error",
    "@typescript-eslint/no-unsafe-type-assertion": "warn",
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": [
      "warn",
      {
        classes: true,
        variables: true,
        enums: true,
        typedefs: true,
        allowNamedExports: true,
        functions: false,
        ignoreTypeReferences: true,
      },
    ],
    "@typescript-eslint/no-useless-empty-export": "error",
    "@typescript-eslint/non-nullable-type-assertion-style": "error",
    "@typescript-eslint/parameter-properties": "off",
    //"@typescript-eslint/parameter-properties": [
    //  "error",
    //  {
    //    prefer: "class-property",
    //    allow: [],
    //  },
    //],
    "@typescript-eslint/prefer-find": "error",
    "@typescript-eslint/prefer-includes": "error",
    "@typescript-eslint/prefer-for-of": "warn",
    "@typescript-eslint/prefer-function-type": "error",
    "@typescript-eslint/prefer-readonly": "warn",
    "@typescript-eslint/prefer-string-starts-ends-with": "error",
    "@typescript-eslint/promise-function-async": "error",
    "@typescript-eslint/require-array-sort-compare": [
      "error",
      { ignoreStringArrays: true },
    ],
    "@typescript-eslint/strict-boolean-expressions": [
      "error",
      {
        allowNullableObject: false,
        allowNullableBoolean: false,
        allowNullableNumber: false,
        allowNullableString: false,
        allowNullableEnum: false,
        allowNumber: false,
        allowString: false,
        allowAny: false,
      },
    ],
  },
  react: {
    // - see: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/README.md#list-of-supported-rules
    // Recommended:
    "react/display-name": "warn",
    "react/jsx-key": "warn",
    "react/jsx-no-comment-textnodes": "warn",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-no-undef": "warn",
    "react/jsx-uses-react": "warn",
    "react/jsx-uses-vars": "warn",
    "react/no-children-prop": "warn",
    "react/no-danger-with-children": "warn",
    "react/no-direct-mutation-state": "warn",
    "react/no-find-dom-node": "warn",
    "react/no-is-mounted": "warn",
    "react/no-render-return-value": "warn",
    "react/no-string-refs": "warn",
    "react/no-unescaped-entities": "warn",
    "react/no-unknown-property": "warn",
    "react/require-render-return": "error",
    // Our rules:
    "react/jsx-no-leaked-render": "error",
    "react/jsx-no-useless-fragment": "warn",
    "react/no-access-state-in-setstate": "error",
    "react/no-array-index-key": "warn",
    "react/no-arrow-function-lifecycle": "warn",
    "react/no-danger": "warn",
    "react/no-deprecated": "warn",
    "react/no-did-mount-set-state": "warn",
    "react/no-did-update-set-state": "warn",
    "react/no-will-update-set-state": "warn",
    "react/no-invalid-html-attribute": "warn",
    "react/no-redundant-should-component-update": "warn",
    "react/no-this-in-sfc": "warn",
    "react/no-typos": "warn",
    "react/no-unsafe": "warn",
    "react/no-unstable-nested-components": "warn",
    "react/void-dom-elements-no-children": "error",
  },
};

export default [
  {
    ignores: ["vendor/**", ".coverage/**"],
  },
  {
    name: "unnamed-project",
    files: ["*.config.{js,cjs}", "src/**/*.{js,jsx,ts,tsx}"],
    ignores: ["src/unnamed_project/gen/*"],
    languageOptions: {
      sourceType: "module",
      ecmaVersion: 2020,
      parser: typescript.parser,
      parserOptions: {
        ecmaFeatures: {
          impliedStrict: true,
          jsx: true,
        },
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.browser,
        React: "readonly",
        GeoJSON: "readonly",
      },
    },
    plugins: {
      react,
      "@typescript-eslint": typescript.plugin,
    },
    settings: {
      react: {
        version: "19",
      },
    },
    rules: {
      ...k_commonRules.eslint,
      ...k_commonRules.typescript,
      ...k_commonRules.react,
    },
  },
  {
    name: "unnamed-project-test",
    files: ["test/**/*.{js,jsx,ts,tsx}"],
    ignores: [],
    languageOptions: {
      sourceType: "module",
      ecmaVersion: 2020,
      parser: typescript.parser,
      parserOptions: {
        ecmaFeatures: {
          impliedStrict: true,
          jsx: true,
        },
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.jest,
        ...globals.browser,
        React: "readonly",
      },
    },
    plugins: {
      jest,
      react,
      "@typescript-eslint": typescript.plugin,
    },
    settings: {
      react: {
        version: "19",
      },
    },
    rules: {
      ...k_commonRules.eslint,
      ...k_commonRules.typescript,
      ...k_commonRules.react,

      // [start] Jest
      // - see: https://github.com/jest-community/eslint-plugin-jest/blob/main/README.md#rules
      // Recommended:
      "jest/expect-expect": "warn",
      "jest/no-alias-methods": "warn",
      "jest/no-conditional-expect": "warn",
      "jest/no-deprecated-functions": "warn",
      "jest/no-disabled-tests": "warn",
      "jest/no-focused-tests": "warn",
      "jest/no-test-prefixes": "error",
      "jest/no-done-callback": "error",
      "jest/no-export": "error",
      "jest/no-identical-title": "error",
      "jest/no-interpolation-in-snapshots": "error",
      "jest/no-jasmine-globals": "error",
      "jest/no-mocks-import": "error",
      "jest/no-standalone-expect": "error",
      "jest/prefer-to-be": "warn",
      "jest/prefer-to-contain": "warn",
      "jest/prefer-to-have-length": "warn",
      "jest/valid-describe-callback": "error",
      "jest/valid-title": ["error", { ignoreTypeOfTestName: true }],
      "jest/valid-expect": "error",
      "jest/valid-expect-in-promise": "error",
      // Our rules:
      "jest/no-confusing-set-timeout": "warn",
      "jest/no-duplicate-hooks": "warn",
      "jest/no-test-return-statement": "error",
      "jest/prefer-called-with": "warn",
      "jest/prefer-comparison-matcher": "warn",
      "jest/prefer-each": "warn",
      "jest/prefer-equality-matcher": "warn",
      "jest/prefer-expect-resolves": "warn",
      "jest/prefer-mock-promise-shorthand": "warn",
      "jest/prefer-strict-equal": "warn",
      "jest/prefer-todo": "warn",
      // [end] Jest
    },
  },
];
